infostring: 'TEST_'

simulations_savedir: '/Users/vatsalpanwar/source/work/astro/projects/Warwick/code/plastar/outputs/'

phoenix_model_dir: '/Users/vatsalpanwar/source/work/astro/projects/Warwick/code/plastar/input_data/phoenix/'
model_resolution_working: 200000
time_range: [-2.,2.] ## in hours
time_step: 30. ## in seconds
time_stamps: [0.] ### set this to None if you want to use the time_range and time_step to generate the time stamps. Otherwise, set this to a list of time stamps in hours.

instrument:
  name: igrins
  resolution: 45000
  wavelength_min: 2300.
  wavelength_max: 2350.
  wavelength_spacing: R ### constant resolving power
  wavelength_unit: 'nm'

star:
  teff: '5000'
  log_g: '4.00'
  met: '0.0'
  # model_flux_fname: 'lte05000-4.00-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits'
  # model_wave_fname: 'WAVE_PHOENIX-ACES-AGSS-COND-2011.fits'
  model_type: 'phoenix'

  Rs: 1.
  nside: 32


  tile_width: 0.02
  subtile_width: 0.001
  inc: 90.
  v_eq: 5.
  alpha: 0.
  u1: 0.5507
  u2: 0.1361
  LD: 'quadratic_phoenix' ## this will override u1 and u2 values. Set to quadratic_self if you want to use self defined LD coefficients.
  # LD: 'uniform' ## No limb darkening.

planet:
  orbper: 2.218577
  transit_duration: 1.84 ## in hours
  inc: 85.690
  omega: 0.
  ecc: 0.
  T0: 0.
  Rp: 0.1504 ## in units of Rstar
  obliquity: 0. #np.pi/2,
  a: 8.73 ## in units of Rstar

spots_and_faculae:
  teff: ['4200', '4200'] ## Use this to also calculate the approx contrast with the stellar surface.
  lat: [0., 10.]
  lon: [0., 10.] 
  rad: [5., 5.] ## Radius of the spot, in degrees.
  sharpness: [500, 800]

  log_g: ['4.00', '4.00']
  met: ['0.0', '0.0']
  # model_flux_fname: ['lte04200-4.00-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits', 'lte04200-4.00-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits']
  # model_wave_fname: ['WAVE_PHOENIX-ACES-AGSS-COND-2011.fits', 'WAVE_PHOENIX-ACES-AGSS-COND-2011.fits']
  model_type: 'phoenix'
  
  cb_sup: [300., 300.] # in m/s
  u1: [0.5507, 0.5507]
  u2: [0.1361, 0.1361]
  LD: 'quadratic_phoenix' ## this will override u1 and u2 values. Set to quadratic_self if you want to use self defined LD coefficients.
    # teff: [4200.] ## Use this to also calculate the approx contrast with the stellar surface.
    # lat: [0.]
    # lon: [0.] 
    # rad: [20.] ## Radius of the spot, in degrees.
    # sharpness: [500]

    # log_g: [4.00]
    # met: [0.0]
    # model_flux_fname: ['lte04200-4.00-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits']
    # model_wave_fname: ['WAVE_PHOENIX-ACES-AGSS-COND-2011.fits']
    # model_type: 'phoenix'
    
    # cb_sup: [300.] # in m/s
    # u1: [0.5507]
    # u2: [0.1361]
    # LD: 'quadratic_phoenix' ## this will override u1 and u2 values. Set to quadratic_self if you want to use self defined LD coefficients.

