infostring: 'TEST_'

simulations_savedir: '/home/astro/phsprd/stellar_activity/data/simulated_obs/'

phoenix_model_dir: '/home/astro/phsprd/stellar_activity/data/input_data/phoenix/'
model_resolution_working: 200000
time_range: None # [-2.,2.] ## in hours, always as measured from primary mid-transit.
phase_range: [0.37, 0.67]
time_step: 300. ## in seconds, including the overheads.
time_stamps: None # [0.] ### set this to None if you want to use the time_range and time_step to generate the time stamps. Otherwise, set this to a list of time stamps in hours.
phase0_star_wrt_mid_transit: 0.37 ## Difference between the phase = 0 of the star's own rotation and the planet's mid-transit, in units of planetary orbital phase.  
seg_length: 100

instrument:
  name: igrins
  resolution: 45000
  wavelength_min: 2360.
  wavelength_max: 2370. ##
  wavelength_spacing: R ### constant resolving power
  wavelength_unit: 'nm'

star:
  teff: '5000'
  log_g: '4.00'
  met: '0.0'
  model_type: 'phoenix'

  Rs: 1. ## In solar radius 
  nside: 128

  inc: 90.
  v_eq: 5.
  alpha: 0.
  u1: 0.5507
  u2: 0.1361
  LD: 'quadratic_phoenix' ## this will override u1 and u2 values. Set to quadratic_self if you want to use self defined LD coefficients.

  # LD: 'uniform' ## No limb darkening.

planet:
  orbper: 2.218577
  impact_param: 0.656

  transit_duration: 1.84 ## in hours
  inc: 85.690
  omega: 0.
  ecc: 0.
  T0: 0.
  Rp_by_Rs: 0.1504 ## in units of Rstar
  obliquity: 0. #np.pi/2,
  a: 8.73 ## in units of Rstar

spots_and_faculae:
  teff: ['4200', '4200'] ## Use this to also calculate the approx contrast with the stellar surface.
  lat: [0., 10.]
  lon: [-45., 45.] 
  rad: [2., 2.] ## Radius of the spot, in degrees.
  sharpness: [500, 800]

  log_g: ['4.00', '4.00']
  met: ['0.0', '0.0']
  model_type: 'phoenix'
  
  cb_sup: [300., 300.] # in m/s
  u1: [0.5507, 0.5507]
  u2: [0.1361, 0.1361]
  LD: 'quadratic_phoenix' ## this will override u1 and u2 values. Set to quadratic_self if you want to use self defined LD coefficients.

