# infostring: 'TEST_emission_dTspot--1100_spot_size-0.2_long-J_band_1120-1125-nm_'
infostring: 'TEST_rev_emission_dTspot--1100_spot_size-0.2_long-K_band_2440-2445-nm_'
method: 'emission'
simulations_savedir: '/home/astro/phsprd/code/plastar/examples/emission/results/'

time_step: 300. ## in seconds, including the overheads.
time_stamps: None # [0.] ### set this to None if you want to use the time_range and time_step to generate the time stamps. Otherwise, set this to a list of time stamps in hours.
phase_range: [0.38, 0.48] ## until 0.48 is ~ 5 hours 
planet_phase_at_star_phase0: 0.38 # 0.37 ## Difference between the phase = 0 of the star's own rotation and the planet's mid-transit, in units of planetary orbital phase.  
wavelength_chunk_length: 500
wavelength_overlap_length: 50
# wavelength_chunk_length: null 
# wavelength_overlap_length: null
model_resolution_working: 200000
instrument:
  name: igrins
  resolution: 45000
  wavelength_min: 2435. # 2440. # 2450 # 1960.
  wavelength_max: 2450. # 2445. # 2460. ##
  wavelength_min_star: 2433. # 2440. # 2450 # 1960.
  wavelength_max_star: 2452. # 2445. # 2460. ##

  wavelength_common_min: 2440.
  wavelength_common_max: 2445.

  # wavelength_min: 1120. # 2440. # 2450 # 1960.
  # wavelength_max: 1125. # 2445. # 2460. ##
  # wavelength_min_star: 1118. # 2440. # 2450 # 1960.
  # wavelength_max_star: 1128. # 2445. # 2460. ##

  # wavelength_min: 2440. # 2440. # 2450 # 1960.
  # wavelength_max: 2445. # 2445. # 2460. ##
  # wavelength_min_star: 2438. # 2440. # 2450 # 1960.
  # wavelength_max_star: 2447. # 2445. # 2460. ##

  # wavelength_min: 2440. # 2440. # 2450 # 1960.
  # wavelength_max: 2445. # 2445. # 2460. ##
  # wavelength_min_star: 2435. # 2440. # 2450 # 1960.
  # wavelength_max_star: 2450. # 2445. # 2460. ##
  wavelength_spacing: R ### constant resolving power
  wavelength_unit: 'nm'
  ### Band boundaries based on CRIRES+ ETC 
  ## Y band : 947 nm to 1121 nm 
  ## J band : 1122 nm to 1357 nm
  ## H band : 1423 nm to 1855 nm
  ## K band : 1904 nm to 2528 nm